Logics application
gringbeeri/test_guru pull request #7
Opened 2022-03-06 22:38 UTC by gringbeeri

2022-05-08 19:18 UTC, d1ma-angel requested changes
Очень много вопросов

2022-05-08 19:18 UTC, d1ma-angel commented on app/assets/stylesheets/application.css
> + *= require styles.css
Смотри логику. 13 строкой ты подключаешь все файлы в папке. 14 строкой подключаешь себя самого. А 15 снова конкретно файл, смысл?

2022-05-08 19:18 UTC, d1ma-angel commented on app/assets/stylesheets/scaffolds.scss
> +body {
Я чет не понял что за скаффолды? У тебя в уроке так обучали?

2022-05-08 19:18 UTC, d1ma-angel commented on app/controllers/answers_controller.rb
> +  def show
`def show; end`

2022-05-08 19:18 UTC, d1ma-angel commented on app/controllers/answers_controller.rb
> +  before_action :find_answer, only: %i[ show edit update destroy ]
зачем лишние пробелы между [ и тектом? Тут применимы все те же правила, что и в рубокопе, только их даже больше

2022-05-08 19:18 UTC, d1ma-angel commented on app/controllers/answers_controller.rb
> +  def edit
`def edit; end`

2022-05-08 19:18 UTC, d1ma-angel commented on app/helpers/application_helper.rb
> +  def current_time
Не понял. Я же, вроде, проверил это в тот раз. Почему это еще не слито?

2022-05-08 19:18 UTC, d1ma-angel commented on app/models/test.rb
> +  has_many :test_passages
Почему они из правильного места переползли в неправильное?

2022-05-08 19:18 UTC, d1ma-angel commented on config/application.rb
> +    config.i18n.default_locale = :en
Не понял. Это зачем? Складывается впечатление, что ты откуда-то скатывал.

2022-05-08 19:18 UTC, d1ma-angel commented on db/migrate/20211021204706_create_users.rb
>        t.string :name
Никогда не редактируй миграции, которые уже улетели в удаленный репозиторий. Представь, что другой разработчик утащил к себе ее и прогнал. А теперь ты ее редактируешь и что у него будет в базе?

2022-05-08 19:18 UTC, d1ma-angel commented on test/controllers/answers_controller_test.rb
> +require "test_helper"
Я так понимаю это автосоздалось?

2022-05-08 19:18 UTC, d1ma-angel commented on app/controllers/test_passages_controller.rb
> +class TestPassagesController < ApplicationController
Так и не понял как начать проходить тест

2022-05-08 19:18 UTC, d1ma-angel commented on app/controllers/tests_controller.rb
> +  def edit
Падает с ошибкой `http://localhost:3000/tests/3/edit`

2022-05-08 19:18 UTC, d1ma-angel commented on app/controllers/tests_controller.rb
> +  def edit
А где edit не падает там даже формы редактирования нет.

2022-05-10 20:47 UTC, gringbeeri commented on test/controllers/answers_controller_test.rb
> +require "test_helper"
Да, я создавал контроллер через миграцию и создалось.

2022-05-10 20:48 UTC, gringbeeri commented on db/migrate/20211021204706_create_users.rb
>        t.string :name
Запомнил, больше не повторится.

2022-05-10 20:48 UTC, gringbeeri commented on config/application.rb
> +    config.i18n.default_locale = :en
В процессе менял для того что видеть ошибки появляющиеся при переходе по url.

2022-05-10 20:48 UTC, gringbeeri commented on app/helpers/application_helper.rb
> +  def current_time
Я случайно предыдущую ветку слил в мастер, получается что эта осталось отрезана.

2022-05-10 20:48 UTC, gringbeeri commented on app/controllers/answers_controller.rb
> +  def edit
Поправил.

2022-05-10 20:49 UTC, gringbeeri commented on app/controllers/answers_controller.rb
> +  before_action :find_answer, only: %i[ show edit update destroy ]
Готово, сделал.

2022-05-10 20:49 UTC, gringbeeri commented on app/controllers/answers_controller.rb
> +  def show
Поправил.

2022-05-10 20:58 UTC, gringbeeri commented on app/controllers/test_passages_controller.rb
> +class TestPassagesController < ApplicationController
<img width="1207" alt="Снимок экрана 2022-05-10 в 23 55 36" src="https://user-images.githubusercontent.com/68374649/167720591-2c3955b6-a927-4752-a78b-78dc0b1bf448.png">

При переходе /tests/ кнопка Start.

2022-05-10 21:04 UTC, gringbeeri commented on app/controllers/tests_controller.rb
> +  def edit
Тоже поправил, форма есть.

2022-05-10 21:04 UTC, gringbeeri commented on app/controllers/tests_controller.rb
> +  def edit
Форму поправил.

2022-05-10 21:16 UTC, gringbeeri commented on app/assets/stylesheets/scaffolds.scss
> +body {
Да, я когда применил скаффолд при создании Answer и файл применился, но я многое до заполнил вручную тут.

2022-05-10 21:21 UTC, gringbeeri commented on app/assets/stylesheets/application.css
> + *= require styles.css
Готово, не подумал что директивой *= require_tree . подключаю итак все файлы в stylesheets.

2022-05-10 21:24 UTC, gringbeeri commented on app/models/test.rb
> +  has_many :test_passages
Поменял местами.

2022-05-26 20:35 UTC, d1ma-angel approved these changes

2022-05-26 20:35 UTC, d1ma-angel commented on app/models/user.rb
> +  def test_passage(test)
Не очень понял, что это делает)

2022-05-29 13:20 UTC, merged